#cloud-config
# Add groups to the system
# Adds the ubuntu group with members 'root' and 'sys'
# and the empty group hashicorp.
groups:
  - ubuntu: [root,sys]
  - hashicorp
# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: deploy
    gecos: deploy
    shell: /bin/bash
    primary_group: hashicorp
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    ssh_authorized_keys: 
      - AAAAB3NzaC1yc2EAAAADAQABAAABgQC2L8mpOPn12yNOJfT+dii1SFXrDfZpj9cY09/3YURXwTzdTHW8xlS3UnIyxKoR7GmXwdf/57sqtb/07BSZ5Cm7YmhLVGhTwjE66lCQH6Lz1i0bfB3Ij4uos7y2eoa1K76h9VBjpntkxmD7Alojp6HXXLvJxp3uJtr356iRKVGIWH4ON/6o2y4w3okeWDBXIVr6oXZADZgwhirFVnEnGVXYmoBVDN83JgtNhzsNb5EBP7hv2uuC4tAk0wt6yKndJiPbpI+NjbEHUMGfH6WZmWpK+wEF+/qKnQVM0m36/HeUwdI2Ts1MK/1LIP572wAF4xzoy1ijDvGntwiMogOC3hLU9UBULvD+ClXd8pas/KEeKIpxuLCEY7iYc4dP2yX5ZBJcfBLH1FNcu5ooIrDliui9lMLucwsO/GK3o8w8pqwnYUC0h/3hGkALE3xVCBCvfTR7PZBZ5j78FH1Jq+LXpTKjjC0sT8VpE0R1rvnJfOxj0b+Zj/+vPJ+277GvGco/jr8= root@LAPTOP-9ND2USRN
# Downloads the golang package
packages:
  - python3
runcmd:
  -   alias python=python3